
== Terms and Definitions

////
Note that the initial notice about terms ("This document uses the terms defined in OGC Policy Directive 49...")
is inserted automatically by Metanorma using the agreed standardised language, and you should not enter it here.
////

[Spatial Reference System] 
A system for establishing spatial positioning. A spatial reference system can use geographic identifiers (place names, for example), coordinates (in which case it is a coordinate reference system), or identifiers with structured geometry (in which case it is a discrete global grid system). Abbreviated to SRS.

[Coordinate System] 
A set of mathematical rules for specifying how coordinates are to be assigned to points.

[Datum] 
A parameter, or set of parameters, that define the position of the origin, the scale, and the orientation of a coordinate system.

[Coordinate Reference System] 
A coordinate system that is related to an object by a datum. Abbreviated to CRS.


=== example term

term used for exemplary purposes

[.source]
<<ISO19101-1>>

NOTE: An example note.

[example]
Here's an example of an example term.
